### ISSUE TITLE
C++14

### ISSUE THREAD

**Issue by EHadoux** [guillaume-bosc/BalanceSpan#2]
Hi, did you consider using C++14 and get rid of all those pointers? a unique_ptr has almost no overhead and simplifies everything imho.
You may get rid of the hash_map warning with this if that's the reason you divide the code into Mac/Linux versions.

**Comment by mehdi-kaytoue** [comment]
Well, a large part of the code relies on the PrefixSpan algorithm that we extended.
This explains why we kept an old coding style :)

**Comment by EHadoux** [comment]
Fair enough. Is the -m32 flag mandatory? It breaks a lot of builds on Travis.

**Comment by EHadoux** [comment]
Okay, after diving a bit into the code, I just give up the idea of modifying it to fit modern coding standards ahah.
I'll open another issue for the right purpose.
However, I fear that any further development will be a bit of a pain :(
